# theme: jekyll-theme-cayman
title: Denys Lazarenko
description: AI Engineer curious about GenAI and Robotics.

highlighter: rouge

header_pages:
  - about.md
  - projects.md

##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true
