# theme: jekyll-theme-cayman
title: Denys Lazarenko
description: Technical University of Munich, Class of 2019

highlighter: rouge

##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true